@Library("groovy-pipeline")

pipeline {
	agent any
	
	stages {
		stage('Build') {
			steps {
			
				@Library("groovy-pipeline")
				pipline() {
					projectName = "Project"
				}
			}				
		}	
	}		
}